; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=mipsel-unknown-linux-gnu -mattr=+micromips -mcpu=mips32r2 \
; RUN: -verify-machineinstrs < %s | FileCheck %s

; RUN: llc -mtriple=mipsel-unknown-linux-gnu -mattr=+micromips -mcpu=mips32r6 \
; RUN: -verify-machineinstrs < %s | FileCheck %s --check-prefix=R6

; Function Attrs: nounwind
define i32 @fun(ptr %adr, i32 %val) {
; CHECK-LABEL: fun:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    addiusp -32
; CHECK-NEXT:    .cfi_def_cfa_offset 32
; CHECK-NEXT:    swm16 $16, $17, $ra, 20($sp) # 12-byte Folded Spill
; CHECK-NEXT:    .cfi_offset 31, -4
; CHECK-NEXT:    .cfi_offset 17, -8
; CHECK-NEXT:    .cfi_offset 16, -12
; CHECK-NEXT:    move $17, $5
; CHECK-NEXT:    move $16, $4
; CHECK-NEXT:    jal fun1
; CHECK-NEXT:    nop
; CHECK-NEXT:    sw16 $17, 0($16)
; CHECK-NEXT:    li16 $2, 0
; CHECK-NEXT:    lwm16 $16, $17, $ra, 20($sp) # 12-byte Folded Reload
; CHECK-NEXT:    addiusp 32
; CHECK-NEXT:    jrc $ra
;
; R6-LABEL: fun:
; R6:       # %bb.0: # %entry
; R6-NEXT:    addiu $sp, $sp, -32
; R6-NEXT:    .cfi_def_cfa_offset 32
; R6-NEXT:    swm16 $16, $17, $ra, 20($sp) # 12-byte Folded Spill
; R6-NEXT:    .cfi_offset 31, -4
; R6-NEXT:    .cfi_offset 17, -8
; R6-NEXT:    .cfi_offset 16, -12
; R6-NEXT:    move $17, $5
; R6-NEXT:    move $16, $4
; R6-NEXT:    balc fun1
; R6-NEXT:    sw16 $17, 0($16)
; R6-NEXT:    li16 $2, 0
; R6-NEXT:    lwm16 $16, $17, $ra, 20($sp) # 12-byte Folded Reload
; R6-NEXT:    addiu $sp, $sp, 32
; R6-NEXT:    jrc $ra
entry:
  %call1 =  call ptr @fun1()
  store i32 %val, ptr %adr, align 4
  ret i32 0
}

declare ptr @fun1()

