; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -O2 -mtriple=mipsel-linux-gnu -global-isel -global-isel-abort=1 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=LE
; RUN: llc -O2 -mtriple=mips-linux-gnu -global-isel -global-isel-abort=1 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=BE
; RUN: llc -O2 -mtriple=mipsel-linux-gnu -mcpu=mips32r6 -global-isel -global-isel-abort=1 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=LE-R6
; RUN: llc -O2 -mtriple=mips-linux-gnu -mcpu=mips32r6 -global-isel -global-isel-abort=1 -verify-machineinstrs %s -o - | FileCheck %s --check-prefix=BE-R6

; Track code-quality improvements for generic memory splitting.
; TODO: Combine the extension into the load before splitting to avoid a final mask.
define i32 @load24(ptr %p) {
; LE-LABEL: load24:
; LE:       # %bb.0:
; LE-NEXT:    lbu $1, 0($4)
; LE-NEXT:    lbu $2, 1($4)
; LE-NEXT:    sll $2, $2, 8
; LE-NEXT:    or $1, $2, $1
; LE-NEXT:    lbu $2, 2($4)
; LE-NEXT:    sll $2, $2, 16
; LE-NEXT:    or $1, $2, $1
; LE-NEXT:    lui $2, 255
; LE-NEXT:    ori $2, $2, 65535
; LE-NEXT:    jr $ra
; LE-NEXT:    and $2, $1, $2
;
; BE-LABEL: load24:
; BE:       # %bb.0:
; BE-NEXT:    lbu $1, 2($4)
; BE-NEXT:    lbu $2, 1($4)
; BE-NEXT:    lbu $3, 0($4)
; BE-NEXT:    sll $3, $3, 8
; BE-NEXT:    or $2, $3, $2
; BE-NEXT:    sll $2, $2, 8
; BE-NEXT:    or $1, $2, $1
; BE-NEXT:    lui $2, 255
; BE-NEXT:    ori $2, $2, 65535
; BE-NEXT:    jr $ra
; BE-NEXT:    and $2, $1, $2
;
; LE-R6-LABEL: load24:
; LE-R6:       # %bb.0:
; LE-R6-NEXT:    lhu $1, 0($4)
; LE-R6-NEXT:    lbu $2, 2($4)
; LE-R6-NEXT:    sll $2, $2, 16
; LE-R6-NEXT:    or $1, $2, $1
; LE-R6-NEXT:    lui $2, 255
; LE-R6-NEXT:    ori $2, $2, 65535
; LE-R6-NEXT:    jr $ra
; LE-R6-NEXT:    and $2, $1, $2
;
; BE-R6-LABEL: load24:
; BE-R6:       # %bb.0:
; BE-R6-NEXT:    lbu $1, 2($4)
; BE-R6-NEXT:    lhu $2, 0($4)
; BE-R6-NEXT:    sll $2, $2, 8
; BE-R6-NEXT:    or $1, $2, $1
; BE-R6-NEXT:    lui $2, 255
; BE-R6-NEXT:    ori $2, $2, 65535
; BE-R6-NEXT:    jr $ra
; BE-R6-NEXT:    and $2, $1, $2
  %v = load i24, ptr %p, align 1
  %r = zext i24 %v to i32
  ret i32 %r
}

; TODO: Remove redundant AND/OR operations after legalization.
define i64 @load40(ptr %p) {
; LE-LABEL: load40:
; LE:       # %bb.0:
; LE-NEXT:    lw $1, 0($4)
; LE-NEXT:    ori $2, $zero, 0
; LE-NEXT:    lbu $3, 4($4)
; LE-NEXT:    or $1, $2, $1
; LE-NEXT:    ori $3, $3, 0
; LE-NEXT:    addiu $2, $zero, 65535
; LE-NEXT:    and $2, $1, $2
; LE-NEXT:    jr $ra
; LE-NEXT:    andi $3, $3, 255
;
; BE-LABEL: load40:
; BE:       # %bb.0:
; BE-NEXT:    lbu $1, 4($4)
; BE-NEXT:    lw $2, 0($4)
; BE-NEXT:    sll $3, $2, 8
; BE-NEXT:    sll $4, $1, 8
; BE-NEXT:    srl $2, $2, 24
; BE-NEXT:    or $2, $4, $2
; BE-NEXT:    or $1, $3, $1
; BE-NEXT:    ori $2, $2, 0
; BE-NEXT:    addiu $3, $zero, 65535
; BE-NEXT:    and $3, $1, $3
; BE-NEXT:    jr $ra
; BE-NEXT:    andi $2, $2, 255
;
; LE-R6-LABEL: load40:
; LE-R6:       # %bb.0:
; LE-R6-NEXT:    lw $1, 0($4)
; LE-R6-NEXT:    ori $2, $zero, 0
; LE-R6-NEXT:    lbu $3, 4($4)
; LE-R6-NEXT:    or $1, $2, $1
; LE-R6-NEXT:    ori $3, $3, 0
; LE-R6-NEXT:    addiu $2, $zero, 65535
; LE-R6-NEXT:    and $2, $1, $2
; LE-R6-NEXT:    jr $ra
; LE-R6-NEXT:    andi $3, $3, 255
;
; BE-R6-LABEL: load40:
; BE-R6:       # %bb.0:
; BE-R6-NEXT:    lbu $1, 4($4)
; BE-R6-NEXT:    lw $2, 0($4)
; BE-R6-NEXT:    sll $3, $2, 8
; BE-R6-NEXT:    sll $4, $1, 8
; BE-R6-NEXT:    srl $2, $2, 24
; BE-R6-NEXT:    or $2, $4, $2
; BE-R6-NEXT:    or $1, $3, $1
; BE-R6-NEXT:    ori $2, $2, 0
; BE-R6-NEXT:    addiu $3, $zero, 65535
; BE-R6-NEXT:    and $3, $1, $3
; BE-R6-NEXT:    jr $ra
; BE-R6-NEXT:    andi $2, $2, 255
  %v = load i40, ptr %p, align 4
  %r = zext i40 %v to i64
  ret i64 %r
}

; TODO: Fold chained pointer offsets into the memory instructions.
define i64 @load48(ptr %p) {
; LE-LABEL: load48:
; LE:       # %bb.0:
; LE-NEXT:    lwl $1, 3($4)
; LE-NEXT:    lwr $1, 0($4)
; LE-NEXT:    ori $2, $zero, 0
; LE-NEXT:    ori $3, $zero, 4
; LE-NEXT:    addu $3, $4, $3
; LE-NEXT:    lbu $4, 4($4)
; LE-NEXT:    lbu $3, 1($3)
; LE-NEXT:    sll $3, $3, 8
; LE-NEXT:    or $3, $3, $4
; LE-NEXT:    or $1, $2, $1
; LE-NEXT:    ori $3, $3, 0
; LE-NEXT:    addiu $2, $zero, 65535
; LE-NEXT:    and $2, $1, $2
; LE-NEXT:    jr $ra
; LE-NEXT:    andi $3, $3, 65535
;
; BE-LABEL: load48:
; BE:       # %bb.0:
; BE-NEXT:    ori $1, $zero, 4
; BE-NEXT:    addu $1, $4, $1
; BE-NEXT:    lbu $1, 1($1)
; BE-NEXT:    lbu $2, 4($4)
; BE-NEXT:    sll $2, $2, 8
; BE-NEXT:    or $1, $2, $1
; BE-NEXT:    lwl $2, 0($4)
; BE-NEXT:    lwr $2, 3($4)
; BE-NEXT:    sll $3, $2, 16
; BE-NEXT:    sll $4, $1, 16
; BE-NEXT:    srl $2, $2, 16
; BE-NEXT:    or $2, $4, $2
; BE-NEXT:    or $1, $3, $1
; BE-NEXT:    ori $2, $2, 0
; BE-NEXT:    addiu $3, $zero, 65535
; BE-NEXT:    and $3, $1, $3
; BE-NEXT:    jr $ra
; BE-NEXT:    andi $2, $2, 65535
;
; LE-R6-LABEL: load48:
; LE-R6:       # %bb.0:
; LE-R6-NEXT:    lw $1, 0($4)
; LE-R6-NEXT:    ori $2, $zero, 0
; LE-R6-NEXT:    lhu $3, 4($4)
; LE-R6-NEXT:    or $1, $2, $1
; LE-R6-NEXT:    ori $3, $3, 0
; LE-R6-NEXT:    addiu $2, $zero, 65535
; LE-R6-NEXT:    and $2, $1, $2
; LE-R6-NEXT:    jr $ra
; LE-R6-NEXT:    andi $3, $3, 65535
;
; BE-R6-LABEL: load48:
; BE-R6:       # %bb.0:
; BE-R6-NEXT:    lhu $1, 4($4)
; BE-R6-NEXT:    lw $2, 0($4)
; BE-R6-NEXT:    sll $3, $2, 16
; BE-R6-NEXT:    sll $4, $1, 16
; BE-R6-NEXT:    srl $2, $2, 16
; BE-R6-NEXT:    or $2, $4, $2
; BE-R6-NEXT:    or $1, $3, $1
; BE-R6-NEXT:    ori $2, $2, 0
; BE-R6-NEXT:    addiu $3, $zero, 65535
; BE-R6-NEXT:    and $3, $1, $3
; BE-R6-NEXT:    jr $ra
; BE-R6-NEXT:    andi $2, $2, 65535
  %v = load i48, ptr %p, align 1
  %r = zext i48 %v to i64
  ret i64 %r
}

define i64 @load56(ptr %p) {
; LE-LABEL: load56:
; LE:       # %bb.0:
; LE-NEXT:    lwl $1, 3($4)
; LE-NEXT:    lwr $1, 0($4)
; LE-NEXT:    ori $2, $zero, 0
; LE-NEXT:    ori $3, $zero, 4
; LE-NEXT:    addu $3, $4, $3
; LE-NEXT:    lbu $4, 4($4)
; LE-NEXT:    lbu $5, 1($3)
; LE-NEXT:    sll $5, $5, 8
; LE-NEXT:    or $4, $5, $4
; LE-NEXT:    lbu $3, 2($3)
; LE-NEXT:    sll $3, $3, 16
; LE-NEXT:    or $3, $3, $4
; LE-NEXT:    or $1, $2, $1
; LE-NEXT:    ori $3, $3, 0
; LE-NEXT:    addiu $2, $zero, 65535
; LE-NEXT:    lui $4, 255
; LE-NEXT:    ori $4, $4, 65535
; LE-NEXT:    and $2, $1, $2
; LE-NEXT:    jr $ra
; LE-NEXT:    and $3, $3, $4
;
; BE-LABEL: load56:
; BE:       # %bb.0:
; BE-NEXT:    ori $1, $zero, 4
; BE-NEXT:    addu $1, $4, $1
; BE-NEXT:    lbu $2, 2($1)
; BE-NEXT:    lbu $1, 1($1)
; BE-NEXT:    lbu $3, 4($4)
; BE-NEXT:    sll $3, $3, 8
; BE-NEXT:    or $1, $3, $1
; BE-NEXT:    sll $1, $1, 8
; BE-NEXT:    or $1, $1, $2
; BE-NEXT:    lwl $2, 0($4)
; BE-NEXT:    lwr $2, 3($4)
; BE-NEXT:    sll $3, $2, 24
; BE-NEXT:    sll $4, $1, 24
; BE-NEXT:    srl $2, $2, 8
; BE-NEXT:    or $2, $4, $2
; BE-NEXT:    or $1, $3, $1
; BE-NEXT:    ori $2, $2, 0
; BE-NEXT:    addiu $3, $zero, 65535
; BE-NEXT:    lui $4, 255
; BE-NEXT:    ori $4, $4, 65535
; BE-NEXT:    and $3, $1, $3
; BE-NEXT:    jr $ra
; BE-NEXT:    and $2, $2, $4
;
; LE-R6-LABEL: load56:
; LE-R6:       # %bb.0:
; LE-R6-NEXT:    lw $1, 0($4)
; LE-R6-NEXT:    ori $2, $zero, 0
; LE-R6-NEXT:    ori $3, $zero, 4
; LE-R6-NEXT:    addu $3, $4, $3
; LE-R6-NEXT:    lhu $4, 4($4)
; LE-R6-NEXT:    lbu $3, 2($3)
; LE-R6-NEXT:    sll $3, $3, 16
; LE-R6-NEXT:    or $3, $3, $4
; LE-R6-NEXT:    or $1, $2, $1
; LE-R6-NEXT:    ori $3, $3, 0
; LE-R6-NEXT:    addiu $2, $zero, 65535
; LE-R6-NEXT:    lui $4, 255
; LE-R6-NEXT:    ori $4, $4, 65535
; LE-R6-NEXT:    and $2, $1, $2
; LE-R6-NEXT:    jr $ra
; LE-R6-NEXT:    and $3, $3, $4
;
; BE-R6-LABEL: load56:
; BE-R6:       # %bb.0:
; BE-R6-NEXT:    ori $1, $zero, 4
; BE-R6-NEXT:    addu $1, $4, $1
; BE-R6-NEXT:    lbu $1, 2($1)
; BE-R6-NEXT:    lhu $2, 4($4)
; BE-R6-NEXT:    sll $2, $2, 8
; BE-R6-NEXT:    or $1, $2, $1
; BE-R6-NEXT:    lw $2, 0($4)
; BE-R6-NEXT:    sll $3, $2, 24
; BE-R6-NEXT:    sll $4, $1, 24
; BE-R6-NEXT:    srl $2, $2, 8
; BE-R6-NEXT:    or $2, $4, $2
; BE-R6-NEXT:    or $1, $3, $1
; BE-R6-NEXT:    ori $2, $2, 0
; BE-R6-NEXT:    addiu $3, $zero, 65535
; BE-R6-NEXT:    lui $4, 255
; BE-R6-NEXT:    ori $4, $4, 65535
; BE-R6-NEXT:    and $3, $1, $3
; BE-R6-NEXT:    jr $ra
; BE-R6-NEXT:    and $2, $2, $4
  %v = load i56, ptr %p, align 1
  %r = zext i56 %v to i64
  ret i64 %r
}

define void @store24(ptr %p, i32 %v) {
; LE-LABEL: store24:
; LE:       # %bb.0:
; LE-NEXT:    srl $1, $5, 16
; LE-NEXT:    srl $2, $5, 8
; LE-NEXT:    sb $5, 0($4)
; LE-NEXT:    sb $2, 1($4)
; LE-NEXT:    jr $ra
; LE-NEXT:    sb $1, 2($4)
;
; BE-LABEL: store24:
; BE:       # %bb.0:
; BE-NEXT:    srl $1, $5, 8
; BE-NEXT:    srl $2, $1, 8
; BE-NEXT:    sb $2, 0($4)
; BE-NEXT:    sb $1, 1($4)
; BE-NEXT:    jr $ra
; BE-NEXT:    sb $5, 2($4)
;
; LE-R6-LABEL: store24:
; LE-R6:       # %bb.0:
; LE-R6-NEXT:    srl $1, $5, 16
; LE-R6-NEXT:    sh $5, 0($4)
; LE-R6-NEXT:    jr $ra
; LE-R6-NEXT:    sb $1, 2($4)
;
; BE-R6-LABEL: store24:
; BE-R6:       # %bb.0:
; BE-R6-NEXT:    srl $1, $5, 8
; BE-R6-NEXT:    sh $1, 0($4)
; BE-R6-NEXT:    jr $ra
; BE-R6-NEXT:    sb $5, 2($4)
  %t = trunc i32 %v to i24
  store i24 %t, ptr %p, align 1
  ret void
}

define void @store48(ptr %p, i64 %v) {
; LE-LABEL: store48:
; LE:       # %bb.0:
; LE-NEXT:    ori $1, $zero, 4
; LE-NEXT:    addu $1, $4, $1
; LE-NEXT:    swl $6, 3($4)
; LE-NEXT:    swr $6, 0($4)
; LE-NEXT:    srl $2, $7, 8
; LE-NEXT:    sb $7, 4($4)
; LE-NEXT:    jr $ra
; LE-NEXT:    sb $2, 1($1)
;
; BE-LABEL: store48:
; BE:       # %bb.0:
; BE-NEXT:    srl $1, $7, 16
; BE-NEXT:    sll $2, $6, 16
; BE-NEXT:    or $1, $1, $2
; BE-NEXT:    ori $2, $zero, 4
; BE-NEXT:    addu $2, $4, $2
; BE-NEXT:    swl $1, 0($4)
; BE-NEXT:    swr $1, 3($4)
; BE-NEXT:    srl $1, $7, 8
; BE-NEXT:    sb $1, 4($4)
; BE-NEXT:    jr $ra
; BE-NEXT:    sb $7, 1($2)
;
; LE-R6-LABEL: store48:
; LE-R6:       # %bb.0:
; LE-R6-NEXT:    sw $6, 0($4)
; LE-R6-NEXT:    jr $ra
; LE-R6-NEXT:    sh $7, 4($4)
;
; BE-R6-LABEL: store48:
; BE-R6:       # %bb.0:
; BE-R6-NEXT:    srl $1, $7, 16
; BE-R6-NEXT:    sll $2, $6, 16
; BE-R6-NEXT:    or $1, $1, $2
; BE-R6-NEXT:    sw $1, 0($4)
; BE-R6-NEXT:    jr $ra
; BE-R6-NEXT:    sh $7, 4($4)
  %t = trunc i64 %v to i48
  store i48 %t, ptr %p, align 1
  ret void
}

define void @store56(ptr %p, i64 %v) {
; LE-LABEL: store56:
; LE:       # %bb.0:
; LE-NEXT:    ori $1, $zero, 4
; LE-NEXT:    addu $1, $4, $1
; LE-NEXT:    swl $6, 3($4)
; LE-NEXT:    swr $6, 0($4)
; LE-NEXT:    srl $2, $7, 16
; LE-NEXT:    srl $3, $7, 8
; LE-NEXT:    sb $7, 4($4)
; LE-NEXT:    sb $3, 1($1)
; LE-NEXT:    jr $ra
; LE-NEXT:    sb $2, 2($1)
;
; BE-LABEL: store56:
; BE:       # %bb.0:
; BE-NEXT:    srl $1, $7, 24
; BE-NEXT:    sll $2, $6, 8
; BE-NEXT:    or $1, $1, $2
; BE-NEXT:    ori $2, $zero, 4
; BE-NEXT:    addu $2, $4, $2
; BE-NEXT:    swl $1, 0($4)
; BE-NEXT:    swr $1, 3($4)
; BE-NEXT:    srl $1, $7, 8
; BE-NEXT:    srl $3, $1, 8
; BE-NEXT:    sb $3, 4($4)
; BE-NEXT:    sb $1, 1($2)
; BE-NEXT:    jr $ra
; BE-NEXT:    sb $7, 2($2)
;
; LE-R6-LABEL: store56:
; LE-R6:       # %bb.0:
; LE-R6-NEXT:    ori $1, $zero, 4
; LE-R6-NEXT:    addu $1, $4, $1
; LE-R6-NEXT:    sw $6, 0($4)
; LE-R6-NEXT:    srl $2, $7, 16
; LE-R6-NEXT:    sh $7, 4($4)
; LE-R6-NEXT:    jr $ra
; LE-R6-NEXT:    sb $2, 2($1)
;
; BE-R6-LABEL: store56:
; BE-R6:       # %bb.0:
; BE-R6-NEXT:    srl $1, $7, 24
; BE-R6-NEXT:    sll $2, $6, 8
; BE-R6-NEXT:    or $1, $1, $2
; BE-R6-NEXT:    ori $2, $zero, 4
; BE-R6-NEXT:    addu $2, $4, $2
; BE-R6-NEXT:    sw $1, 0($4)
; BE-R6-NEXT:    srl $1, $7, 8
; BE-R6-NEXT:    sh $1, 4($4)
; BE-R6-NEXT:    jr $ra
; BE-R6-NEXT:    sb $7, 2($2)
  %t = trunc i64 %v to i56
  store i56 %t, ptr %p, align 1
  ret void
}

; Retain the padding-bit mask while removing operations on undefined high bits.
; TODO: Fold shifts of undefined high bits to zero before combining the pieces.
define i64 @load42(ptr %p) {
; LE-LABEL: load42:
; LE:       # %bb.0:
; LE-NEXT:    lwl $1, 3($4)
; LE-NEXT:    lwr $1, 0($4)
; LE-NEXT:    ori $2, $zero, 0
; LE-NEXT:    ori $3, $zero, 4
; LE-NEXT:    addu $3, $4, $3
; LE-NEXT:    lbu $4, 4($4)
; LE-NEXT:    lbu $3, 1($3)
; LE-NEXT:    sll $3, $3, 8
; LE-NEXT:    or $3, $3, $4
; LE-NEXT:    or $1, $2, $1
; LE-NEXT:    ori $3, $3, 0
; LE-NEXT:    addiu $2, $zero, 65535
; LE-NEXT:    and $2, $1, $2
; LE-NEXT:    jr $ra
; LE-NEXT:    andi $3, $3, 1023
;
; BE-LABEL: load42:
; BE:       # %bb.0:
; BE-NEXT:    ori $1, $zero, 4
; BE-NEXT:    addu $1, $4, $1
; BE-NEXT:    lbu $1, 1($1)
; BE-NEXT:    lbu $2, 4($4)
; BE-NEXT:    sll $2, $2, 8
; BE-NEXT:    or $1, $2, $1
; BE-NEXT:    lwl $2, 0($4)
; BE-NEXT:    lwr $2, 3($4)
; BE-NEXT:    sll $3, $2, 16
; BE-NEXT:    sll $4, $1, 16
; BE-NEXT:    srl $2, $2, 16
; BE-NEXT:    or $2, $4, $2
; BE-NEXT:    or $1, $3, $1
; BE-NEXT:    ori $2, $2, 0
; BE-NEXT:    addiu $3, $zero, 65535
; BE-NEXT:    and $3, $1, $3
; BE-NEXT:    jr $ra
; BE-NEXT:    andi $2, $2, 1023
;
; LE-R6-LABEL: load42:
; LE-R6:       # %bb.0:
; LE-R6-NEXT:    lw $1, 0($4)
; LE-R6-NEXT:    ori $2, $zero, 0
; LE-R6-NEXT:    lhu $3, 4($4)
; LE-R6-NEXT:    or $1, $2, $1
; LE-R6-NEXT:    ori $3, $3, 0
; LE-R6-NEXT:    addiu $2, $zero, 65535
; LE-R6-NEXT:    and $2, $1, $2
; LE-R6-NEXT:    jr $ra
; LE-R6-NEXT:    andi $3, $3, 1023
;
; BE-R6-LABEL: load42:
; BE-R6:       # %bb.0:
; BE-R6-NEXT:    lhu $1, 4($4)
; BE-R6-NEXT:    lw $2, 0($4)
; BE-R6-NEXT:    sll $3, $2, 16
; BE-R6-NEXT:    sll $4, $1, 16
; BE-R6-NEXT:    srl $2, $2, 16
; BE-R6-NEXT:    or $2, $4, $2
; BE-R6-NEXT:    or $1, $3, $1
; BE-R6-NEXT:    ori $2, $2, 0
; BE-R6-NEXT:    addiu $3, $zero, 65535
; BE-R6-NEXT:    and $3, $1, $3
; BE-R6-NEXT:    jr $ra
; BE-R6-NEXT:    andi $2, $2, 1023
  %v = load i42, ptr %p, align 1
  %r = zext i42 %v to i64
  ret i64 %r
}

define i32 @sextload24(ptr %p) {
; LE-LABEL: sextload24:
; LE:       # %bb.0:
; LE-NEXT:    lbu $1, 0($4)
; LE-NEXT:    lbu $2, 1($4)
; LE-NEXT:    sll $2, $2, 8
; LE-NEXT:    or $1, $2, $1
; LE-NEXT:    lbu $2, 2($4)
; LE-NEXT:    sll $2, $2, 16
; LE-NEXT:    or $1, $2, $1
; LE-NEXT:    sll $1, $1, 8
; LE-NEXT:    jr $ra
; LE-NEXT:    sra $2, $1, 8
;
; BE-LABEL: sextload24:
; BE:       # %bb.0:
; BE-NEXT:    lbu $1, 2($4)
; BE-NEXT:    lbu $2, 1($4)
; BE-NEXT:    lbu $3, 0($4)
; BE-NEXT:    sll $3, $3, 8
; BE-NEXT:    or $2, $3, $2
; BE-NEXT:    sll $2, $2, 8
; BE-NEXT:    or $1, $2, $1
; BE-NEXT:    sll $1, $1, 8
; BE-NEXT:    jr $ra
; BE-NEXT:    sra $2, $1, 8
;
; LE-R6-LABEL: sextload24:
; LE-R6:       # %bb.0:
; LE-R6-NEXT:    lhu $1, 0($4)
; LE-R6-NEXT:    lbu $2, 2($4)
; LE-R6-NEXT:    sll $2, $2, 16
; LE-R6-NEXT:    or $1, $2, $1
; LE-R6-NEXT:    sll $1, $1, 8
; LE-R6-NEXT:    jr $ra
; LE-R6-NEXT:    sra $2, $1, 8
;
; BE-R6-LABEL: sextload24:
; BE-R6:       # %bb.0:
; BE-R6-NEXT:    lbu $1, 2($4)
; BE-R6-NEXT:    lhu $2, 0($4)
; BE-R6-NEXT:    sll $2, $2, 8
; BE-R6-NEXT:    or $1, $2, $1
; BE-R6-NEXT:    sll $1, $1, 8
; BE-R6-NEXT:    jr $ra
; BE-R6-NEXT:    sra $2, $1, 8
  %v = load i24, ptr %p, align 1
  %r = sext i24 %v to i32
  ret i32 %r
}
