; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --print-fixed-stack
; RUN: llc -mtriple=mips-linux-gnu -global-isel -global-isel-abort=1 -stop-after=irtranslator -verify-machineinstrs %s -o - | FileCheck %s

; Generic registers use least-significant-part-first order. O32 big-endian
; argument and return locations put the most significant word first instead.
define i64 @register_i64(i64 %x) {
  ; CHECK-LABEL: name: register_i64
  ; CHECK: fixedStack:
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $a0, $a1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $a1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $a0
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY]](s32), [[COPY1]](s32)
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[MV]](s64)
  ; CHECK-NEXT:   $v1 = COPY [[UV]](s32)
  ; CHECK-NEXT:   $v0 = COPY [[UV1]](s32)
  ; CHECK-NEXT:   RetRA implicit $v1, implicit $v0
  ret i64 %x
}

define i64 @stack_i64(i32 %a, i32 %b, i32 %c, i32 %d, i64 %x) {
  ; CHECK-LABEL: name: stack_i64
  ; CHECK: fixedStack:
  ; CHECK-NEXT:   - { id: 0, type: default, offset: 16, size: 4, alignment: 8, stack-id: default,
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK-NEXT:   - { id: 1, type: default, offset: 20, size: 4, alignment: 4, stack-id: default,
  ; CHECK-NEXT:       isImmutable: true, isAliased: false, callee-saved-register: '', callee-saved-restored: true,
  ; CHECK-NEXT:       debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $a0, $a1, $a2, $a3
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $a0
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $a1
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $a2
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $a3
  ; CHECK-NEXT:   [[FRAME_INDEX:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.1
  ; CHECK-NEXT:   [[LOAD:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX]](p0) :: (load (s32) from %fixed-stack.1)
  ; CHECK-NEXT:   [[FRAME_INDEX1:%[0-9]+]]:_(p0) = G_FRAME_INDEX %fixed-stack.0
  ; CHECK-NEXT:   [[LOAD1:%[0-9]+]]:_(s32) = G_LOAD [[FRAME_INDEX1]](p0) :: (load (s32) from %fixed-stack.0, align 8)
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[LOAD]](s32), [[LOAD1]](s32)
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[MV]](s64)
  ; CHECK-NEXT:   $v1 = COPY [[UV]](s32)
  ; CHECK-NEXT:   $v0 = COPY [[UV1]](s32)
  ; CHECK-NEXT:   RetRA implicit $v1, implicit $v0
  ret i64 %x
}

declare i64 @callee_i64(i32, i64)
declare i64 @callee_stack_i64(i32, i32, i32, i32, i64)

define i64 @call_i64(i64 %x) {
  ; CHECK-LABEL: name: call_i64
  ; CHECK: fixedStack:
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $a0, $a1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $a1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $a0
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY]](s32), [[COPY1]](s32)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 16, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[MV]](s64)
  ; CHECK-NEXT:   $a0 = COPY [[C]](s32)
  ; CHECK-NEXT:   $a3 = COPY [[UV]](s32)
  ; CHECK-NEXT:   $a2 = COPY [[UV1]](s32)
  ; CHECK-NEXT:   JAL @callee_i64, csr_o32, implicit-def $ra, implicit-def $sp, implicit $a0, implicit $a3, implicit $a2, implicit-def $v1, implicit-def $v0
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(s32) = COPY $v1
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(s32) = COPY $v0
  ; CHECK-NEXT:   [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY2]](s32), [[COPY3]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKUP 16, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[MV1]](s64)
  ; CHECK-NEXT:   $v1 = COPY [[UV2]](s32)
  ; CHECK-NEXT:   $v0 = COPY [[UV3]](s32)
  ; CHECK-NEXT:   RetRA implicit $v1, implicit $v0
  %v = call i64 @callee_i64(i32 1, i64 %x)
  ret i64 %v
}

define i64 @call_stack_i64(i64 %x) {
  ; CHECK-LABEL: name: call_stack_i64
  ; CHECK: fixedStack:
  ; CHECK: bb.1 (%ir-block.0):
  ; CHECK-NEXT:   liveins: $a0, $a1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:_(s32) = COPY $a1
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:_(s32) = COPY $a0
  ; CHECK-NEXT:   [[MV:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY]](s32), [[COPY1]](s32)
  ; CHECK-NEXT:   [[C:%[0-9]+]]:_(s32) = G_CONSTANT i32 1
  ; CHECK-NEXT:   [[C1:%[0-9]+]]:_(s32) = G_CONSTANT i32 2
  ; CHECK-NEXT:   [[C2:%[0-9]+]]:_(s32) = G_CONSTANT i32 3
  ; CHECK-NEXT:   [[C3:%[0-9]+]]:_(s32) = G_CONSTANT i32 4
  ; CHECK-NEXT:   ADJCALLSTACKDOWN 24, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[UV:%[0-9]+]]:_(s32), [[UV1:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[MV]](s64)
  ; CHECK-NEXT:   [[COPY2:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C4:%[0-9]+]]:_(s32) = G_CONSTANT i32 20
  ; CHECK-NEXT:   [[PTR_ADD:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY2]], [[C4]](s32)
  ; CHECK-NEXT:   G_STORE [[UV]](s32), [[PTR_ADD]](p0) :: (store (s32) into stack + 20)
  ; CHECK-NEXT:   [[COPY3:%[0-9]+]]:_(p0) = COPY $sp
  ; CHECK-NEXT:   [[C5:%[0-9]+]]:_(s32) = G_CONSTANT i32 16
  ; CHECK-NEXT:   [[PTR_ADD1:%[0-9]+]]:_(p0) = G_PTR_ADD [[COPY3]], [[C5]](s32)
  ; CHECK-NEXT:   G_STORE [[UV1]](s32), [[PTR_ADD1]](p0) :: (store (s32) into stack + 16, align 8)
  ; CHECK-NEXT:   $a0 = COPY [[C]](s32)
  ; CHECK-NEXT:   $a1 = COPY [[C1]](s32)
  ; CHECK-NEXT:   $a2 = COPY [[C2]](s32)
  ; CHECK-NEXT:   $a3 = COPY [[C3]](s32)
  ; CHECK-NEXT:   JAL @callee_stack_i64, csr_o32, implicit-def $ra, implicit-def $sp, implicit $a0, implicit $a1, implicit $a2, implicit $a3, implicit-def $v1, implicit-def $v0
  ; CHECK-NEXT:   [[COPY4:%[0-9]+]]:_(s32) = COPY $v1
  ; CHECK-NEXT:   [[COPY5:%[0-9]+]]:_(s32) = COPY $v0
  ; CHECK-NEXT:   [[MV1:%[0-9]+]]:_(s64) = G_MERGE_VALUES [[COPY4]](s32), [[COPY5]](s32)
  ; CHECK-NEXT:   ADJCALLSTACKUP 24, 0, implicit-def $sp, implicit $sp
  ; CHECK-NEXT:   [[UV2:%[0-9]+]]:_(s32), [[UV3:%[0-9]+]]:_(s32) = G_UNMERGE_VALUES [[MV1]](s64)
  ; CHECK-NEXT:   $v1 = COPY [[UV2]](s32)
  ; CHECK-NEXT:   $v0 = COPY [[UV3]](s32)
  ; CHECK-NEXT:   RetRA implicit $v1, implicit $v0
  %v = call i64 @callee_stack_i64(i32 1, i32 2, i32 3, i32 4, i64 %x)
  ret i64 %v
}
